#!/bin/sh

set -e

case "$1" in
    install|upgrade)
      if ! getent group timetracker >/dev/null; then
        addgroup --system timetracker
      fi
      if ! getent passwd timetracker >/dev/null; then
        adduser --system timetracker --ingroup timetracker --no-create-home --disabled-password
      fi
    ;;

    abort-upgrade)
    ;;

    *)
        echo "preinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0