#!/bin/sh

set -e

case "$1" in
    remove|deconfigure)
      if getent passwd timetracker >/dev/null; then
        deluser --system timetracker
      fi
      if getent group timetracker >/dev/null; then
        delgroup --system timetracker
      fi

      update-alternatives --remove-all timetracker
    ;;

    upgrade)
    ;;

    failed-upgrade)
    ;;

    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0