# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.18'

    - name: Test UI
      run: go test -cover -v go test ronnyfriedland/timetracker/v2/ui

    - name: Test CLI
      run: go test -cover -v go test ronnyfriedland/timetracker/v2/cli

    - name: Test Logic
      run: go test -cover -v go test ronnyfriedland/timetracker/v2/logic

    - name: Build UI
      run: go build -o build/timetracker-ui ronnyfriedland/timetracker/v2/ui

    - name: Build CLI
      run: go build -o build/timetracker-cli ronnyfriedland/timetracker/v2/cli

